package com.everglow.backend.reviews;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;

/**
 * Entity class representing customer feedback/reviews
 * for vendors in the system.
 */
@Entity
@Table(name = "feedbacks")
@Data                   // Generates getters, setters, toString, equals, hashCode
@NoArgsConstructor      // Generates no-argument constructor
@AllArgsConstructor     // Generates constructor with all fields
@Builder                // Enables Builder pattern
public class Feedback {

    /**
     * Primary key of the feedback table.
     * Auto-incremented by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * ID of the user who submitted the feedback.
     * Cannot be null.
     */
    @Column(name = "user_id", nullable = false)
    @NotNull(message = "User ID is required")
    private Long userId;

    /**
     * ID of the vendor receiving the feedback.
     * Cannot be null.
     */
    @Column(name = "vendor_id", nullable = false)
    @NotNull(message = "Vendor ID is required")
    private Long vendorId;

    /**
     * Related booking ID (optional).
     * Used to connect feedback with a booking.
     */
    @Column(name = "booking_id")
    private Long bookingId;

    /**
     * Rating value given by the user.
     * Must be between 1 and 5.
     */
    @Column(nullable = false)
    @Min(value = 1, message = "Rating must be at least 1")
    @Max(value = 5, message = "Rating must be at most 5")
    private Integer rating;

    /**
     * User comment/review text.
     * Cannot be blank and maximum length is 1000 characters.
     */
    @Column(columnDefinition = "TEXT")
    @NotBlank(message = "Comment cannot be blank")
    @Size(max = 1000, message = "Comment cannot exceed 1000 characters")
    private String comment;

    /**
     * Name of the reviewer.
     * Maximum length is 100 characters.
     */
    @Column(name = "reviewer_name", length = 100)
    private String reviewerName;

    /**
     * Category of the vendor.
     * Example: Catering, Photography, Decoration, etc.
     */
    @Column(name = "vendor_category", length = 100)
    private String vendorCategory;

    /**
     * Approval status of the feedback.
     * Default value is false until approved by admin/moderator.
     */
    @Column(nullable = false)
    @Builder.Default
    private Boolean approved = false;

    /**
     * Timestamp when the feedback was created.
     * Automatically generated by Hibernate.
     */
    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    /**
     * Timestamp when the feedback was last updated.
     * Automatically updated by Hibernate.
     */
    @UpdateTimestamp
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;
}