spring.application.name=backend
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server.port=8081
spring.datasource.url=${postgresql://neondb_owner:npg_UJ6nYNoerBT0@ep-rough-frog-aoorv8b6-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require}
spring.datasource.username=${neondb_owner}
spring.datasource.password=${npg_UJ6nYNoerBT0}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true